export const REQUEST_RAND_QUOTES = 'QUOTE/REQUEST_RAND_QUOTES'

export const REQUEST_QUOTES = 'QUOTE/REQUEST_QUOTES'

export const FETCH_QUOTES = 'QUOTE/FETCH_QUOTES'

export const REQUEST_CATEGORIES = 'CATEGORY/REQUEST_CATEGORIES'

export const FETCH_CATEGORIES = 'CATEGORY/FETCH_CATEGORIES'

export const SHOW_ALERT = 'ALERT/SHOW_ALERT'





